const fs=require('fs'),{JSDOM}=require('jsdom');
const F='/home/user/conda/tier-unification/Project-Profiler.html';
const d=new JSDOM(fs.readFileSync(F,'utf8'),{runScripts:'dangerously',pretendToBeVisual:true,url:'https://local/'});
const w=d.window,dc=w.document;w.alert=()=>{};w.scrollTo=()=>{};
w.URL.createObjectURL=()=>'blob:x';w.URL.revokeObjectURL=()=>{};
const S=w.eval('state');
const click=el=>el.dispatchEvent(new w.MouseEvent('click',{bubbles:true}));
const set=(id,v)=>{const o=[...dc.querySelectorAll('.opt[data-id="'+id+'"]')].find(x=>x.dataset.v===v);if(o&&!o.classList.contains('sel'))click(o);};
set('impact','public');set('spend','l');set('coord','3');set('data','y');set('sec','n');
w.__revealed=true; click(dc.getElementById('revealBtn'));
S.__ackContra={C1:'DK'}; w.updateExportGate();
let cap=null; const ow=w.XLSX.write; w.XLSX.write=function(wb,o){cap=wb;return ow.call(this,wb,o);};
w.saveAsExcel();
const fail=[];const ok=(n,c,g)=>{console.log((c?'  PASS ':'  FAIL ')+n+(g!==undefined?'  ('+g+')':''));if(!c)fail.push(n);};
ok('Contradictions sheet present', cap.SheetNames.includes('Contradictions'));
const cs=w.XLSX.utils.sheet_to_json(cap.Sheets['Contradictions'],{header:1});
ok('Contradictions header correct', cs[0].join(',')==='contradiction_id,severity,fired,acknowledged,ack_initials,message', cs[0].join(','));
const c1=cs.find(r=>r[0]==='C1');
ok('C1 fired=Y acknowledged=Y initials=DK', c1&&c1[2]==='Y'&&c1[3]==='Y'&&c1[4]==='DK', c1&&c1.slice(0,5).join(','));
const fields=w.XLSX.utils.sheet_to_json(cap.Sheets['Fields'],{header:1});
const fmap=Object.fromEntries(fields.map(r=>[r[0],r[1]]));
ok('ans_sec=n', fmap.ans_sec==='n', fmap.ans_sec);
ok('ans_data=y', fmap.ans_data==='y', fmap.ans_data);
ok('security_fired=Y (pii)', fmap.security_fired==='Y', fmap.security_fired);
ok('Contradictions sheet hidden', (cap.Workbook.Sheets[cap.SheetNames.indexOf('Contradictions')]||{}).Hidden===1);
console.log('\n'+(fail.length?fail.length+' FAIL':'F1 HANDOFF OK'));
process.exit(fail.length?1:0);
